### ISSUE TITLE
Could you update this plugin to exiled 5.3.0

### ISSUE THREAD

**Issue by Oyplap** [LilNesquuik/SinkholesRedux#1]
Im not sure why but the plugin doesnt seem to work on that version.

**Comment by LilNesquuik** [comment]
Did you have an error ?

**Comment by LilNesquuik** [comment]
https://github.com/LilNesquuik/SinkholesRedux/releases/tag/EXILED5.3.0

**Comment by Oyplap** [comment]
Works! Thank you for helping me out :D
