### ISSUE TITLE
[BUG] Peanut tantrum causes people to fall into the pocket dimension

### ISSUE THREAD

**Issue by Oyplap** [LilNesquuik/SinkholesRedux#2]
I'm using https://github.com/LilNesquuik/SinkholesRedux/tree/EXILED5.3.0 and when people stand on scp-173 tantrum, everybody falls into the pocket dimension.

**Comment by LilNesquuik** [comment]
Its fix soon

**Comment by LilNesquuik** [comment]
https://github.com/LilNesquuik/SinkholesRedux/releases/tag/V0.1.1

**Comment by LilNesquuik** [comment]
Tell me if its not fix and if its fix

**Comment by Oyplap** [comment]
> Tell me if its not fix and if its fix

Thanks!

**Comment by LilNesquuik** [comment]
Sorry for the wait in France it is 4:54am 💤

**Comment by Oyplap** [comment]
No problem at all, I live in The Netherlands, same time

**Comment by LilNesquuik** [comment]
Oh ok :) if you have a problem tell me but for the moment i go to sleep

**Comment by Oyplap** [comment]
> Oh ok :) if you have a problem tell me but for the moment i go to sleep

New update broke the plugin a bit, nobody can fall through the sinkhole anymore.

**Comment by LilNesquuik** [comment]
I fix it in 5 minutes

**Comment by Oyplap** [comment]
Thanks! Could you also perhaps add a config to change the falling speed?

**Comment by LilNesquuik** [comment]
> 
I Fix the plugin and if i have the time yes i can add falling speed

**Comment by LilNesquuik** [comment]
Okay its fix i upload in 2 minutes

**Comment by LilNesquuik** [comment]
https://github.com/LilNesquuik/SinkholesRedux/releases/tag/V0.1.1

**Comment by LilNesquuik** [comment]
Try with tantrum and tell me

**Comment by Oyplap** [comment]
> Try with tantrum and tell me

everything works, but now no one can escape the pocket dimension. You get teleported back to the middle of the pocket dimension's room. Also the pocket dimension doesn't give damage

**Comment by LilNesquuik** [comment]
Did you have test with 106debug ?

**Comment by Oyplap** [comment]
where is that config?

**Comment by LilNesquuik** [comment]
Add my on discord LilNesquuik#1028
